import = ["/home/artty/.config/alacritty/themes/themes/monokai_pro.toml", "/home/artty/.config/alacritty/fonts/cascadia.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 1

[window.padding]
x = 2
