font:
  normal:
    family: B612Mono
    style: Regular

  bold:
    family: B612Mono
    style: Bold

  italic:
    family: B612Mono
    style: Italic

  bold_italic:
    family: B612Mono
    style: BoldItalic

  size: 9
