[font]
size = 10

[font.bold]
family = "CascadiaCodePL"
style = "SemiBold"

[font.bold_italic]
family = "CascadiaCodePL"
style = "SemiBoldItalic"

[font.italic]
family = "CascadiaCodePL"
style = "SemiBoldItalic"

[font.normal]
family = "CascadiaCodePL"
style = "Regular"
