font:
  normal:
    family: FantasqueSansMono
    style: Regular

  bold:
    family: FantasqueSansMono
    style: Bold

  italic:
    family: FantasqueSansMono
    style: Italic

  bold_italic:
    family: FantasqueSansMono
    style: BoldItalic

  size: 10
