font:
  normal:
    family: SourceCodePro
    style: Semibold

  bold:
    family: SourceCodePro
    style: Semibold

  italic:
    family: SourceCodePro
    style: Italic

  bold_italic:
    family: SourceCodePro
    style: SemiboldIt

  size: 10
